version: '3.8'

services:
  org:
    build: .
    environment:
      # Connect to remote state
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      # ---
    volumes:
      - ./:/app
