version: '3.8'

services:
  org:
    build: .
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      TF_VAR_AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      TF_VAR_AWS_PROFILE: ${AWS_PROFILE}
      TF_VAR_AWS_REGION: ${AWS_DEFAULT_REGION}
      TF_VAR_AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./:/app
