version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  build:
    docker:
      - image: alpine:3
    steps:
        - run: echo "Hello world!"

  deploy-to-production:
    docker:
      - image: alpine:3
    steps:
      - run: echo "Hello world!"

  deploy-to-staging:
    docker:
      - image: alpine:3
    steps:
      - run: echo "Hello world!"

  release:
    docker:
      - image: alpine:3
    steps:
      - run: echo "Hello world!"

  test:
    docker:
      - image: alpine:3
    steps:
      - run: echo "Hello world!"

workflows:
  success:
    jobs:
      - build
      # - deploy-to-production
      # - deploy-to-staging
      # - release
      # - test
