name: happy-day-ci

on:
  push:
    paths:
      - 'services/happy-day/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run build script
        working-directory: ./services/happy-day
        run: bash ./build.sh
