name: organization-ci

on:
  push:
    paths:
      - 'organization/**'

defaults:
  run:
    working-directory: ./organization

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_PROFILE: ${{ secrets.AWS_PROFILE }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy-to-production:
    container: 1mill/terraform-sops:2020-07-02_03-40-45
    if: endsWith(github.ref, 'master') == true
    needs: [test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: bash ./ci-deploy.bash

  test:
    container: 1mill/terraform-sops:2020-07-02_03-40-45
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: bash ./ci-test.bash
