name: happy-day-ci

on:
  push:
    paths:
      - 'services/happy-day/**'

jobs:
  build:
    defaults:
        run:
          working-directory: ./services/hello-world
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run build script
        run: bash ./build.bash
