name: happy-day-ci

on:
  push:
    paths:
      - 'services/happy-day/**'

defaults:
  run:
    working-directory: ./services/happy-day

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - run: bash ./build.bash

  deploy-to-production:
    if: endsWith(github.ref, 'master') == true
    needs: [build, test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Deploy to production
        env:
          ENVIRONMENT: production
        run: bash ./deploy.bash

  deploy-to-staging:
    if: endsWith(github.ref, 'development') == true
    needs: [build, test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Deploy to staging
        env:
          ENVIRONMENT: staging
        run: bash ./deploy.bash

  test:
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - run: bash ./test.bash
